/**
 * @file main.ts
 * @description Main module for event-handler registration and user interactions.
 */

import { updateCodePreview, updateMinHeightBasedOnMode } from './codePreview.ts';
import './core/applogger.ts';
import { initDownloadFunctionality } from './downloadApp.ts';
import { initExtendedOptions } from './extendedOptions.ts';
import { initFileInputListener } from './fileInput.ts';
import { paymentMethodsTab } from './globals.ts';
import { initErrorCodesSystem } from './modals/errorCodes.ts';
import { initInputParametersModal, showParameterModal } from './modals/inputParameters.ts';
import { initOutputParametersModal } from './modals/outputParameters.ts';
import { initializePaymentUrlBuilder } from './paymentUrlBuilder.ts';

import { initEmailConfirmationListeners } from './emailConfirmation.ts';
import { EventListeners } from './eventListenersClass.ts';
import { initKeyboardShortcuts } from './keyboardShortcuts.ts';
import {
	initAutoGeneratedPlaceholders,
	initPlaceholder,
	setupPlaceholderStyling,
} from './placeholders.ts';
import {
	handleCredentialBlur,
	handleCredentialFocus,
	loadCredentials,
	loadState,
	setObfuscatedCredential,
} from './session.ts';
import { initSlicePayDepartureDate } from './slicepayDepartureDate.ts';
import { initThemeToggle } from './theme.ts';
import { initTooltips, initTruncationTooltips } from './tooltips.ts';
import { updateActionButtonsState } from './ui/buttonState.ui.ts';
import { initDisplayModeDropdown } from './displayMode.ts';
import { initPaymentModeDropdown } from './paymentMode.ts';
import { initUserModeDropdown } from './userMode.ts';
import { initOverrideFeePayerDropdown } from './overrideFeePayer.ts';

/**
 * Initialize the entire application with all required modules and event listeners
 * @returns Promise that resolves when initialization is complete
 * @example
 * ```typescript
 * // Initialize the application
 * await initializeApp();
 * ```
 */
export async function initializeApp(): Promise<void> {
	try {
		// Initialize header elements

		// Initialize tooltips and UI components
		initTooltips();
		initTruncationTooltips(); // Auto-show full value on hover for truncated fields

		// Initialize all listeners using the new class approach
		const eventListeners = new EventListeners();
		eventListeners.initAllListeners();
		initFileInputListener();
		initKeyboardShortcuts();

		// Initialize URL and email listeners (handled by initializePaymentUrlBuilder)
		initEmailConfirmationListeners();
		initDisplayModeDropdown();
		initPaymentModeDropdown();
		initUserModeDropdown();
		initOverrideFeePayerDropdown();

		// Initialize theme and UI components
		initThemeToggle();
		initializePaymentUrlBuilder(true);
		initExtendedOptions({ generateCustomerData: false });
		initPlaceholder();
		setupPlaceholderStyling();
		initAutoGeneratedPlaceholders(); // Set random placeholders for fields

		// Payment-specific listeners are now handled by EventListeners class

		// Restore session data
		const credentials = loadCredentials();
		if (credentials) {
			const apiKeyInput = document.getElementById('apiKeyInput') as HTMLInputElement;
			const usernameInput = document.getElementById('usernameInput') as HTMLInputElement;
			const passwordInput = document.getElementById('passwordInput') as HTMLInputElement;
			const merchantCodeInput = document.getElementById('merchantCodeInput') as HTMLInputElement;

			if (apiKeyInput) apiKeyInput.value = credentials.apiKey;
			if (merchantCodeInput) merchantCodeInput.value = credentials.merchantCode;

			// Obfuscate username and password
			if (usernameInput && credentials.username) {
				setObfuscatedCredential(usernameInput, credentials.username);
			}
			if (passwordInput && credentials.password) {
				setObfuscatedCredential(passwordInput, credentials.password);
			}

			// Setup focus/blur handlers for credential obfuscation
			usernameInput?.addEventListener('focus', () => handleCredentialFocus(usernameInput));
			usernameInput?.addEventListener('blur', () => handleCredentialBlur(usernameInput));
			passwordInput?.addEventListener('focus', () => handleCredentialFocus(passwordInput));
			passwordInput?.addEventListener('blur', () => handleCredentialBlur(passwordInput));
		}

		const state = loadState();
		if (state) {
			// Restore callback URL
			const callbackUrlInput = document.getElementById('callbackUrlInput') as HTMLInputElement;
			if (callbackUrlInput) callbackUrlInput.value = state.callbackUrl;

			// Restore mode
			const modeSelect = document.getElementById('modeSelect') as HTMLSelectElement;
			if (modeSelect && state.mode) modeSelect.value = state.mode;

			// Restore departure date
			const departureDateInput = document.getElementById('departureDateInput') as HTMLInputElement;
			if (departureDateInput && state.departureDate) departureDateInput.value = state.departureDate;

			// Helper to update toggle state
			const updateToggle = (id: string, value: boolean) => {
				const toggle = document.getElementById(id) as HTMLInputElement;
				if (toggle) toggle.checked = value;
			};

			// Restore payment method toggles
			Object.assign(paymentMethodsTab, state.paymentMethods);
			updateToggle('allowBankAcOneOffPayment', state.paymentMethods.allowBankAcOneOffPayment);
			updateToggle('allowPayToOneOffPayment', state.paymentMethods.allowPayToOneOffPayment);
			updateToggle('allowPayIdOneOffPayment', state.paymentMethods.allowPayIdOneOffPayment);
			updateToggle('allowApplePayOneOffPayment', state.paymentMethods.allowApplePayOneOffPayment);
			updateToggle('allowGooglePayOneOffPayment', state.paymentMethods.allowGooglePayOneOffPayment);
			updateToggle('allowSlicePayOneOffPayment', state.paymentMethods.allowSlicePayOneOffPayment);
			updateToggle('allowSaveCardUserOption', state.paymentMethods.allowSaveCardUserOption);

			// Restore option toggles
			if (state.options) {
				updateToggle(
					'sendConfirmationEmailToCustomer',
					state.options.sendConfirmationEmailToCustomer
				);
				updateToggle(
					'sendConfirmationEmailToMerchant',
					state.options.sendConfirmationEmailToMerchant
				);
				updateToggle('hideTermsAndConditions', state.options.hideTermsAndConditions);
				updateToggle('hideMerchantLogo', state.options.hideMerchantLogo);
				updateToggle('showFeeOnTokenising', state.options.showFeeOnTokenising);
				updateToggle(
					'showFailedPaymentFeeOnTokenising',
					state.options.showFailedPaymentFeeOnTokenising
				);

				// Restore radio button states
				const userModeRadio = document.querySelector(
					`input[name="userMode"][value="${state.options.userMode}"]`
				) as HTMLInputElement;
				if (userModeRadio) userModeRadio.checked = true;

				const feePayerRadio = document.querySelector(
					`input[name="overrideFeePayer"][value="${state.options.overrideFeePayer}"]`
				) as HTMLInputElement;
				if (feePayerRadio) feePayerRadio.checked = true;
			}

			console.log('[initializeApp] Payment state restored from session storage');
		}

		updateMinHeightBasedOnMode();
		updateCodePreview();

		// Update action buttons state if available
		if (typeof updateActionButtonsState === 'function') {
			updateActionButtonsState();
		} else {
			console.warn('[main] updateActionButtonsState not available after session restoration');
		}

		// Initialize download functionality
		initDownloadFunctionality('#downloadDemoBtn');

		// Initialize error codes system
		initErrorCodesSystem();

		// Initialize parameter modals
		initInputParametersModal();
		initOutputParametersModal();

		// Initialize SlicePay departure date functionality
		initSlicePayDepartureDate();

		// Make showParameterModal globally available for info icons
		window.showParameterModal = showParameterModal;

		console.log('[main] Application initialization completed successfully');
	} catch (error) {
		console.error('[main] Error during application initialization:', error);
		throw new Error(
			`Application initialization failed: ${error instanceof Error ? error.message : 'Unknown error'}`
		);
	}
}

/**
 * Initialize the application when the DOM is ready
 */
document.addEventListener('DOMContentLoaded', () => {
	initializeApp().catch((error) => {
		console.error('[main] Failed to initialize application:', error);
	});
});
