/**
 * @file main.ts
 * @description Main module for event-handler registration and user interactions.
 */

import { updateCodePreview, updateMinHeightBasedOnMode } from './codePreview.ts';
import './core/applogger.ts';
import { initDownloadFunctionality } from './downloadApp.ts';
import { initExtendedOptions } from './extendedOptions.ts';
import { initFileInputListener } from './fileInput.ts';
import { paymentMethodsTab } from './globals.ts';
import { initErrorCodesSystem } from './modals/errorCodes.ts';
import { initInputParametersModal, showParameterModal } from './modals/inputParameters.ts';
import { initOutputParametersModal } from './modals/outputParameters.ts';
import { initializePaymentUrlBuilder } from './paymentUrlBuilder.ts';

import { initEmailConfirmationListeners } from './emailConfirmation.ts';
import { EventListeners } from './eventListenersClass.ts';
import { initKeyboardShortcuts } from './keyboardShortcuts.ts';
import {
	initAutoGeneratedPlaceholders,
	initPlaceholder,
	setupPlaceholderStyling,
} from './placeholders.ts';
import {
	handleCredentialBlur,
	handleCredentialFocus,
	loadCredentials,
	loadState,
	setObfuscatedCredential,
} from './session.ts';
import { initSlicePayDepartureDate } from './slicepayDepartureDate.ts';
import { initThemeToggle } from './theme.ts';
import { initTooltips, initTruncationTooltips } from './tooltips.ts';
import { updateActionButtonsState } from './ui/buttonState.ui.ts';
import { initDisplayModeDropdown } from './displayMode.ts';
import { initPaymentModeDropdown } from './paymentMode.ts';
import { initUserModeDropdown } from './userMode.ts';
import { initOverrideFeePayerDropdown } from './overrideFeePayer.ts';

/**
 * Initialize core UI components including tooltips and event listeners
 */
function initializeUIComponents(): void {
	initTooltips();
	initTruncationTooltips();

	const eventListeners = new EventListeners();
	eventListeners.initAllListeners();
	initFileInputListener();
	initKeyboardShortcuts();
}

/**
 * Initialize dropdown menus and configuration systems
 */
function initializeDropdownsAndConfiguration(): void {
	initEmailConfirmationListeners();
	initDisplayModeDropdown();
	initPaymentModeDropdown();
	initUserModeDropdown();
	initOverrideFeePayerDropdown();

	initThemeToggle();
	initializePaymentUrlBuilder(true);
	initExtendedOptions({ generateCustomerData: false });
	initPlaceholder();
	setupPlaceholderStyling();
	initAutoGeneratedPlaceholders();
}

/**
 * Restore user credentials from session storage and set up obfuscation handlers
 */
function restoreCredentials(): void {
	const credentials = loadCredentials();
	if (!credentials) {
		return;
	}

	const apiKeyInput = document.getElementById('apiKeyInput') as HTMLInputElement;
	const usernameInput = document.getElementById('usernameInput') as HTMLInputElement;
	const passwordInput = document.getElementById('passwordInput') as HTMLInputElement;
	const merchantCodeInput = document.getElementById('merchantCodeInput') as HTMLInputElement;

	if (apiKeyInput) apiKeyInput.value = credentials.apiKey;
	if (merchantCodeInput) merchantCodeInput.value = credentials.merchantCode;

	if (usernameInput && credentials.username) {
		setObfuscatedCredential(usernameInput, credentials.username);
	}
	if (passwordInput && credentials.password) {
		setObfuscatedCredential(passwordInput, credentials.password);
	}

	usernameInput?.addEventListener('focus', () => handleCredentialFocus(usernameInput));
	usernameInput?.addEventListener('blur', () => handleCredentialBlur(usernameInput));
	passwordInput?.addEventListener('focus', () => handleCredentialFocus(passwordInput));
	passwordInput?.addEventListener('blur', () => handleCredentialBlur(passwordInput));
}

/**
 * Helper function to update toggle checkbox state
 */
function updateToggle(id: string, value: boolean): void {
	const toggle = document.getElementById(id) as HTMLInputElement;
	if (toggle) toggle.checked = value;
}

/**
 * Restore payment method toggles from saved state
 */
function restorePaymentMethods(paymentMethods: typeof paymentMethodsTab): void {
	Object.assign(paymentMethodsTab, paymentMethods);
	updateToggle('allowBankAcOneOffPayment', paymentMethods.allowBankAcOneOffPayment);
	updateToggle('allowPayToOneOffPayment', paymentMethods.allowPayToOneOffPayment);
	updateToggle('allowPayIdOneOffPayment', paymentMethods.allowPayIdOneOffPayment);
	updateToggle('allowApplePayOneOffPayment', paymentMethods.allowApplePayOneOffPayment);
	updateToggle('allowGooglePayOneOffPayment', paymentMethods.allowGooglePayOneOffPayment);
	updateToggle('allowSlicePayOneOffPayment', paymentMethods.allowSlicePayOneOffPayment);
	updateToggle('allowSaveCardUserOption', paymentMethods.allowSaveCardUserOption);
}

/**
 * Restore application options and radio button states from saved state
 */
function restoreOptions(options: NonNullable<ReturnType<typeof loadState>>['options']): void {
	if (!options) {
		return;
	}

	updateToggle('sendConfirmationEmailToCustomer', options.sendConfirmationEmailToCustomer);
	updateToggle('sendConfirmationEmailToMerchant', options.sendConfirmationEmailToMerchant);
	updateToggle('hideTermsAndConditions', options.hideTermsAndConditions);
	updateToggle('hideMerchantLogo', options.hideMerchantLogo);
	updateToggle('showFeeOnTokenising', options.showFeeOnTokenising);
	updateToggle('showFailedPaymentFeeOnTokenising', options.showFailedPaymentFeeOnTokenising);

	const userModeRadio = document.querySelector(
		`input[name="userMode"][value="${options.userMode}"]`
	) as HTMLInputElement;
	if (userModeRadio) userModeRadio.checked = true;

	const feePayerRadio = document.querySelector(
		`input[name="overrideFeePayer"][value="${options.overrideFeePayer}"]`
	) as HTMLInputElement;
	if (feePayerRadio) feePayerRadio.checked = true;
}

/**
 * Restore application state from session storage including callback URL, mode, and all toggles
 */
function restoreApplicationState(): void {
	const state = loadState();
	if (!state) {
		return;
	}

	const callbackUrlInput = document.getElementById('callbackUrlInput') as HTMLInputElement;
	if (callbackUrlInput) callbackUrlInput.value = state.callbackUrl;

	const modeSelect = document.getElementById('modeSelect') as HTMLSelectElement;
	if (modeSelect && state.mode) modeSelect.value = state.mode;

	const departureDateInput = document.getElementById('departureDateInput') as HTMLInputElement;
	if (departureDateInput && state.departureDate) departureDateInput.value = state.departureDate;

	restorePaymentMethods(state.paymentMethods);
	restoreOptions(state.options);

	console.log('[initializeApp] Payment state restored from session storage');
}

/**
 * Initialize modals and additional functionality systems
 */
function initializeModalsAndSystems(): void {
	initDownloadFunctionality('#downloadDemoBtn');
	initErrorCodesSystem();
	initInputParametersModal();
	initOutputParametersModal();
	initSlicePayDepartureDate();

	window.showParameterModal = showParameterModal;
}

/**
 * Finalize initialization by updating UI state and action buttons
 */
function finalizeInitialization(): void {
	updateMinHeightBasedOnMode();
	updateCodePreview();

	if (typeof updateActionButtonsState === 'function') {
		updateActionButtonsState();
	} else {
		console.warn('[main] updateActionButtonsState not available after session restoration');
	}
}

/**
 * Initialize the entire application with all required modules and event listeners
 * @returns Promise that resolves when initialization is complete
 * @example
 * ```typescript
 * // Initialize the application
 * await initializeApp();
 * ```
 */
export async function initializeApp(): Promise<void> {
	try {
		initializeUIComponents();
		initializeDropdownsAndConfiguration();
		restoreCredentials();
		restoreApplicationState();
		finalizeInitialization();
		initializeModalsAndSystems();

		console.log('[main] Application initialization completed successfully');
	} catch (error) {
		console.error('[main] Error during application initialization:', error);
		throw new Error(
			`Application initialization failed: ${error instanceof Error ? error.message : 'Unknown error'}`
		);
	}
}

/**
 * Initialize the application when the DOM is ready
 */
document.addEventListener('DOMContentLoaded', () => {
	initializeApp().catch((error) => {
		console.error('[main] Failed to initialize application:', error);
	});
});
